'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AngryIrishManSoundboard.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AFuckenAyShur() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AFuckenAyShur", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AFuckRingYou() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AFuckRingYou", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AndDontGiveMeNoShake() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AndDontGiveMeNoShake", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AndIDontKnowHowMuchItIs() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AndIDontKnowHowMuchItIs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AndIDontKnowWhatTheHIreOfTheMIs() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AndIDontKnowWhatTheHIreOfTheMIs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AndWithYouChippingAway() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AndWithYouChippingAway", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Arght() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Arght", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AYouListenToFuckenMe() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AYouListenToFuckenMe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Belch() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Belch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property CanYeHearMe() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("CanYeHearMe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property CANYOUFUCKINHEARMENOWYOUSTUPIDCANT() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("CANYOUFUCKINHEARMENOWYOUSTUPIDCANT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property classic() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("classic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property DontActTheCantBecauseYouFarAway() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("DontActTheCantBecauseYouFarAway", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property HangUpPt1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("HangUpPt1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property HangUpPt2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("HangUpPt2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property HowLongAreYouStoopingDownForFric() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("HowLongAreYouStoopingDownForFric", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Huller() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Huller", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property IDontHIreNOOneOut() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("IDontHIreNOOneOut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property IsThatRightShur() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("IsThatRightShur", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ITellYouThisAManyTimes() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ITellYouThisAManyTimes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ManYouAreSomeAssHole() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ManYouAreSomeAssHole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property NahImNotAtNoBase() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("NahImNotAtNoBase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property NaightThatsRite() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("NaightThatsRite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Naw() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Naw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property NawWellUThoughtFockenRong() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("NawWellUThoughtFockenRong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property NawWeMadMoreMeh() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("NawWeMadMoreMeh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property NowSoIfYoureAskingAboutHIgherPrices() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("NowSoIfYoureAskingAboutHIgherPrices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property PriceTalkPt1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("PriceTalkPt1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property PriceTalkPt2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("PriceTalkPt2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Rite() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Rite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SeeWhenYouGetCloseToMe() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SeeWhenYouGetCloseToMe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SoJustYouGetThatOutOfYourFockenHead() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SoJustYouGetThatOutOfYourFockenHead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SoWhatAreYouRingingMeAtThisTimeOfNiteFor() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SoWhatAreYouRingingMeAtThisTimeOfNiteFor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Untitled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Wat() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Wat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property WellIJust() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("WellIJust", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property WellYouThoughtFuckenWrongThatsWhatUThought() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("WellYouThoughtFuckenWrongThatsWhatUThought", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property WhatsWhat() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("WhatsWhat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Wot() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Wot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property YaFuckinBollocksYa() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("YaFuckinBollocksYa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Yes() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Yes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property YouFockenKnowWell() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("YouFockenKnowWell", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property YouFuckenAssHole() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("YouFuckenAssHole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property YouFuckenBollocksYe() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("YouFuckenBollocksYe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property YouStupidAssHole() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("YouStupidAssHole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property YouStupidCant() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("YouStupidCant", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
